version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
    - JVM_OPTS: -Xmx4g
    - ANDROID_HOME: '/opt/android/sdk'
    steps:
    - run:
        name: node-install
        command: |
          curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
          sudo apt-get install -y nodejs
    - run:
        name: gradle-install
        command: 'sudo apt install gradle'
    - checkout
    - run:
        name: git-clone-phonegap-app-developer-keys
        command: |
          git clone https://github.com/phonegap/phonegap-app-developer-keys
          cp -r ./phonegap-app-developer-keys/keys/android/ ./resources/signing/android
    - run:
        name: npm-install
        command: 'npm install'
#    - run:
#        name: build-android
#        command: './resources/circle-ci/android/build-android.sh'
    - run:
        name: aws-install
        command: 'pip install awscli --upgrade --user'
    - run:
        name: aws-ping
        command: |
          export PATH=~/.local/bin:$PATH
          aws --version
    - run:
        name: upload-aws
        command: './resources/circle-ci/android/aws-upload.sh'
    - run:
        name: upload-hockeyapp
        command: 'node ./resources/script/hockey-app.js $HOCKEY_APP_TOKEN $HOCKEY_APP_ANDROID_ID $CIRCLE_SHA1'
